export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const SIGNUP_REQUEST_SUCCESS = 'SIGNUP_REQUEST_SUCCESS';
export const CHANGE_REMEMBER_ME = 'CHANGE_REMEMBER_ME';
export const LOGOUT = 'LOGOUT';
