export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const CLEAN_PRODUCTS_LIST_SUCCESS = 'CLEAN_PRODUCTS_LIST_SUCCESS';
export const ADD_OR_REMOVE_FROM_FAVORITE = 'ADD_OR_REMOVE_TO_FAVORITE';
